MahjongPantheon/Mimir

- .travis.yml
- README.md
- bin/unit.php
- composer.json
- composer.lock
- index.php
- phpunit.xml
- src/Api.php
- tests/ApiTest.php
Add basic test runner, code style linting, travis integration
> Test runner

- .gitignore
- Makefile
- bin/rpc.php
- config/routes.php
- src/Controller.php
- src/controllers/Games.php
- src/exceptions/BadAction.php
- src/exceptions/Database.php
- src/exceptions/InvalidUser.php
- src/exceptions/MalformedPayload.php
- src/fixtures/init/ansi.sql
- src/helpers/Rounds.php
- src/helpers/Users.php
- src/interfaces/IDb.php
- tests/GamesTest.php
- tests/RoundsHelperTest.php
- tests/SortitionTest.php
- tests/util/Db.php
Implement some game-related methods
> Basic tournament methods

- config/rulesets/ema.php
- config/rulesets/jpmlA.php
- config/rulesets/tenhounet.php
- src/Ruleset.php
- src/controllers/Games.php
- src/helpers/YakuMap.php
- src/models/Session.php
- src/primitives/Round.php
- src/validators/Round.php
- tests/helpers/YakuMapTest.php
- tests/models/SessionTest.php
- tests/util/MockRuleset.php
- tests/validators/RoundsTest.php
> Support yaku

- config/routes.php
- src/Api.php
- src/Config.php
- src/Db.php
- src/controllers/Players.php
> Added user controller, fixed db

- README.md
- composer.json
- composer.lock
- src/Db.php
- src/Primitive.php
- src/controllers/Players.php
- src/fixtures/init/ansi.sql
- src/interfaces/IDb.php
- src/models/PlayerStat.php
- src/primitives/Session.php
- src/primitives/SessionResults.php
- src/validators/playerStatSchema.json
- tests/models/TextmodeSessionWholeEventTest.php
- tests/primitives/SessionTest.php
- tests/util/Db.php
> Player event stats and graphs

- config/routes.php
- src/Primitive.php
- src/controllers/Events.php
- src/controllers/Games.php
- src/fixtures/init/ansi.sql
- src/models/Event.php
- src/models/InteractiveSession.php
- src/primitives/PlayerHistory.php
- src/primitives/Session.php
- src/validators/ratingTableSchema.json
- tests/models/InteractiveSessionTest.php
- tests/models/TextmodeSessionWholeEventTest.php
- tests/primitives/PlayerHistoryTest.php
> Event rating table

- composer.json
- composer.lock
- src/Primitive.php
- src/controllers/Events.php
- src/models/Event.php
- src/primitives/MultiRound.php
- src/primitives/PlayerHistory.php
- src/primitives/Round.php
- src/primitives/Session.php
- src/validators/gamesListSchema.json
- tests/models/TextmodeSessionWholeEventTest.php
- tests/primitives/RoundTest.php
- tests/primitives/SessionTest.php
> Last games view

- config/routes.php
- config/rulesets/ema.php
- config/rulesets/jpmlA.php
- config/rulesets/tenhounet.php
- src/Primitive.php
- src/Ruleset.php
- src/controllers/Events.php
- src/controllers/Games.php
- src/controllers/Players.php
- src/fixtures/init/ansi.sql
- src/helpers/onlineLog/Parser.php
- src/models/OnlineSession.php
- src/models/PlayerStat.php
- src/primitives/Event.php
- src/primitives/Session.php
- src/validators/Round.php
- src/validators/playerStatSchema.json
- tests/helpers/onlineLog/ParserTest.php
- tests/helpers/textLog/ParserTest.php
- tests/models/InteractiveSessionTest.php
- tests/models/TextmodeSessionWholeEventTest.php
- tests/util/MockRuleset.php
> Доработки для статборда

- APIDOC.md
- config/routes.php
- src/controllers/Events.php
- src/fixtures/init/ansi.sql
- src/primitives/Event.php
- tests/RealApiTest.php
> Implement timer api

- APIDOC.md
- config/routes.php
- src/controllers/Players.php
- src/helpers/PointsCalc.php
- src/primitives/Session.php
разнообразные фиксы для поддержки фич в мобилке
> Fixes for interactivity mode

- APIDOC.md
- config/index.php
- config/routes.php
- src/Api.php
- src/Controller.php
- src/Model.php
- src/Primitive.php
- src/controllers/Events.php
- src/controllers/Games.php
- src/controllers/Players.php
- src/exceptions/AuthFailed.php
- src/fixtures/init/ansi.sql
- src/helpers/onlineLog/Parser.php
- src/models/Event.php
- src/models/InteractiveSession.php
- src/primitives/Event.php
- src/primitives/PlayerEnrollment.php
- src/primitives/PlayerRegistration.php
- tests/bootstrap.php
- tests/helpers/onlineLog/ParserTest.php
- tests/helpers/textLog/ParserTest.php
- tests/models/InteractiveSessionTest.php
- tests/models/TextmodeSessionWholeEventTest.php
> Tournament auth

- config/rulesets/ema.php
- config/rulesets/jpmlA.php
- src/Ruleset.php
- tests/models/InteractiveSessionTest.php
- tests/rulesets/emaTest.php
- tests/rulesets/jpmlATest.php
https://trello.com/c/l3CmuZp5/17-backend
https://trello.com/c/jzMUvVSk/21-backend-8-4-4-8
https://trello.com/c/F2NBhcoZ/23-backend-35-35-29-21-8-4-58-31-31-0-3-1
> Platform fixes

- APIDOC.md
- config/routes.php
- config/rulesets/jpmlA.php
- src/controllers/Seating.php
- src/helpers/SessionState.php
- tests/helpers/SessionStateTest.php
- tests/models/InteractiveSessionTest.php
- tests/primitives/SessionResultsTest.php
https://trello.com/c/MyHCzWVK/14-backend
https://trello.com/c/7QFLc0KW/27-backend-jpml-a-agariyame-tempaiyame-nashi
https://trello.com/c/1Ot9mcms/35-backend-110317-16-20-1-5-9-13
> Platform fixes 1

- config/rulesets/jpmlA.php
- src/controllers/Events.php
- src/primitives/Event.php
- tests/models/InteractiveSessionTest.php
https://github.com/Furiten/riichi-gui/pull/16
> Platform fixes 2

- APIDOC.md
- config/routes.php
- config/rulesets/tenhounet.php
- src/controllers/Players.php
- src/helpers/PointsCalc.php
- src/helpers/SessionState.php
- src/models/InteractiveSession.php
- src/primitives/MultiRound.php
- tests/RealApiTest.php
https://trello.com/c/Qyqvf4d6/30-frontend
> Platform fixes 3

- config/rulesets/ema.php
- config/rulesets/jpmlA.php
- config/rulesets/jpmlB.php
- config/rulesets/tenhounet.php
- src/Ruleset.php
- src/controllers/Events.php
- src/controllers/Games.php
- src/helpers/SessionState.php
- src/primitives/Event.php
- src/primitives/Session.php
- tests/helpers/SessionStateTest.php
- tests/models/InteractiveSessionTest.php
- tests/primitives/SessionResultsTest.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-29
> MIMIR-29 introduce yellow zone setting

- README.md
- src/controllers/Players.php
- src/helpers/MultiRound.php
- src/models/Event.php
- src/models/InteractiveSession.php
- src/primitives/MultiRound.php
- src/primitives/Session.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-36
> Mimir 36 table state multiround support

- src/models/Event.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-41
> MIMIR-41 fix winner zone coloring for EMA

- Makefile
- src/controllers/Events.php
- src/fixtures/init/ansi.sql
- src/fixtures/init/mysql.sql
- src/fixtures/init/postgres.sql
- src/fixtures/init/sqlite.sql
- src/fixtures/migrations/20170501.sql
- src/fixtures/migrations/mysql/20170501.sql
- src/fixtures/migrations/postgres/20170501.sql
- src/fixtures/migrations/sqlite/20170501.sql
- src/models/Event.php
- src/primitives/Event.php
- tests/primitives/EventTest.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-42
> Mimir 42 split eventtype field

- src/controllers/Events.php
- src/fixtures/init/mysql.sql
- src/fixtures/init/postgres.sql
- src/fixtures/init/sqlite.sql
- src/fixtures/migrations/mysql/20170501.sql
- src/fixtures/migrations/postgres/20170501.sql
- src/fixtures/migrations/sqlite/20170501.sql
- src/primitives/Event.php
- src/primitives/Session.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-44
> MIMIR-44 new field: use timer

- README.md
- nginx.example.conf
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-35
> MIMIR-35 example nginx config

- config/routes.php
- src/controllers/Events.php
- src/models/Event.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-46
> MIMIR-46 tables state by token

- APIDOC.md
- config/routes.php
- src/controllers/Events.php
- src/controllers/Games.php
- src/controllers/Players.php
- src/primitives/Event.php
- src/primitives/PlayerRegistration.php
- tests/RealApiTest.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-49
> MIMIR-49 api fixes

- bin/deploy-staging.sh
- data/seeds/TournamentStagingSeeder.php
- src/Config.php
> MIMIR-47 add seeding script

- Postman collection/Furiten test.postman_environment.json
- Postman collection/Furiten.postman_collection.json
- Postman collection/Furiten.postman_environment.json
- actual values in test environment
- erase values in prod environment
- create folder structure for methods
- some other minor changes in requests (fix bodies, add scripts, etc)
> Update environments & collection:

- src/models/InteractiveSession.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-54
> MIMIR-54 Notify tracker on game start too

- src/models/PlayerStat.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-53
> MIMIR-53 add lost riichi in draws and abortive draws

- APIDOC.md
- data/migrations/20170526130552_update_version1m1m1.php
- src/Date.php
- src/controllers/Events.php
- src/primitives/Event.php
- src/primitives/Session.php
- tests/RealApiTest.php
- tests/helpers/SessionStateTest.php
- tests/helpers/onlineLog/ParserTest.php
- tests/helpers/textLog/ParserTest.php
- tests/models/InteractiveSessionTest.php
- tests/models/TextmodeSessionWholeEventTest.php
- tests/primitives/EventTest.php
- tests/primitives/PlayerHistoryTest.php
- tests/primitives/RoundTest.php
- tests/primitives/SessionResultsTest.php
- tests/primitives/SessionTest.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-51
> MIMIR-51 add timezones to events

- src/Meta.php
- src/controllers/Events.php
- src/controllers/Players.php
- src/models/Event.php
- src/primitives/Session.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-58
> MIMIR-58 add universal watcher user

- APIDOC.md
- config/routes.php
- src/controllers/Events.php
- src/models/Event.php
- src/primitives/Achievements.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-55
Частичные наброски
> MIMIR-55 some achievements

- config/rulesets/tenhounet.php
- data/migrations/20170608064220_add_use_penalty_flag.php
- src/controllers/Events.php
- src/models/InteractiveSession.php
- src/primitives/Event.php
- tests/models/InteractiveSessionTest.php
Еще добавил тест на добавление штрафа
> Add "use_penalty" new event flag

- data/migrations/20170827184753_add_avg_score.php
- src/controllers/Events.php
- src/models/Event.php
- src/primitives/PlayerHistory.php
- src/validators/ratingTableSchema.json
- tests/primitives/PlayerHistoryTest.php
https://pantheon.myjetbrains.com/youtrack/agiles/82-2/83-2
> PANTHEON-10 add average score support & rating sorting

- src/models/OnlineSession.php
- src/primitives/Session.php
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-75
https://pantheon.myjetbrains.com/youtrack/issue/MIMIR-76
> Fix game edning when timer policy is "none"

- src/controllers/Events.php
https://pantheon.myjetbrains.com/youtrack/issue/RHEDA-48
> Add event description
